### ISSUE TITLE
Upgrade to jekyll 3.2

### ISSUE THREAD

**Issue by bibliotechy** [code4lib/2017.code4lib.org#2]
[Github pages now uses jekyll 3.2](https://github.com/blog/2236-github-pages-now-runs-jekyll-3-2)

**Comment by phette23** [comment]
The site appears to run fine locally on Jekyll 3.2. Unless I'm mistaken, we can't test on GitHub pages since we have the DNS configured for the "2017.codelib.org" domain (visiting https://2017.code4lib.org.github.io doesn't work).

I'm leaving this open tentatively but assuming it should not require further work, when we get code4lib.org setup then we can revisit & close.

**Comment by phette23** [comment]
Aaaaand it works fine. http://2017.code4lib.org/
